const functions = require("firebase-functions");
const admin = require("firebase-admin");
const cors = require("cors")({ origin: true });

admin.initializeApp();
const db = admin.firestore();

exports.submitShippingForm = functions.https.onRequest((req, res) => {
  cors(req, res, async () => {
    if (req.method !== "POST") {
      return res.status(405).send("Method Not Allowed");
    }

    try {
      const { fullName, email, address, city, postalCode, province, phone, cartItems } = req.body;

      if (!email || !cartItems || !Array.isArray(cartItems) || cartItems.length === 0) {
        return res.status(400).send("Missing required fields or cart is empty.");
      }

      // Save customer profile (shipping info)
      await db.collection("customers").doc(email).set({
        fullName,
        email,
        address,
        city,
        postalCode,
        province,
        phone,
        lastOrderDate: admin.firestore.FieldValue.serverTimestamp()
      }, { merge: true });

      // Create order with autogenerated ID
      const orderRef = db.collection("orders").doc();
      const orderData = {
        orderId: orderRef.id,
        email,
        fullName,
        address,
        city,
        postalCode,
        province,
        phone,
        items: cartItems, // array of product info
        status: "Pending Payment",
        placedAt: admin.firestore.FieldValue.serverTimestamp()
      };

      await orderRef.set(orderData);

      res.status(200).send({
        message: "Shipping form and order saved successfully",
        orderId: orderRef.id
      });

    } catch (error) {
      console.error("Error saving form or order:", error);
      res.status(500).send("Error submitting form: " + error.message);
    }
  });
});